### ISSUE TITLE
If Aki.Server.exe stops running and is restarted, all in-raid progress is lost for anyone that isn't the host

### ISSUE THREAD

**Issue by Daemris** [project-fika/Fika-Server#29] opened 2024-06-14 18:35 UTC
I host a progress server and often host the Fika server. Sometimes, for some reason, the progress server (Aki.Server.exe) will close. 

When the progress server closes, the Fika server will continue to run with no indication that the progress server closed. (Maybe an in-game warning?) Upon raid end Fika server clients will have lost all in-raid progress and their games will fail to load back to the menu. The only solution is to Alt+F4.

Hosts of the Fika server will not lose any progress so long as they wait for all clients to 'time out' after extraction.
Hosts of single-player fika servers will also not lose any progress so long as the server is restarted before extraction.

I believe this is because Fika references some 'players' variable which is not actually populated with information in the event the server is restarted. Perhaps this information could be stored in a non-volatile way in the event the progress server dies?

**Comment by Lacyway** [comment] 2024-06-14 23:19
I have been playing SPT since September quite extensively and my server has *never* crashed. Can I ask what is causing your random shutdowns? Any logs indicating anything? While I am open to finding a solution, I am also concerned with the root of your problem.

**Comment by Daemris** [comment] 2024-06-16 05:52
I've played SPT for a few years and have also generally never had a server crash before this run.

[2024.06.14_21-51-55_0.14.1.2.29197 errors.log](https://github.com/user-attachments/files/15856318/2024.06.14_21-51-55_0.14.1.2.29197.errors.log)

I don't feel like any of these errors should be responsible for this.

Mods in use:

(\BepInEx\Plugins)
- Waypoints
- Donuts
- RaidOverhaul
- SAIN
- That's Lit
- RamCleanerInterval
- BigBrain
- SearchOpenContainers
- Fika.Core
- LootingBots

(\user\mods)
- AlgorithmicLevelProgression
- Fika-Server
- RaidOverhaul
- RealisticThermals
- ServerValueModifier
- NoDiscardLimit
- SWAG
- SAIN

**Comment by nexus4880** [comment] 2024-06-16 07:01
We would need server logs located in /user/logs.

**Comment by Daemris** [comment] 2024-06-16 16:57
I have edited the message with the most recent log in /user/logs/. Nothing in those logs seems like it would be indicative of a failure either.

**Comment by fariparedes** [comment] 2024-06-17 16:52
You can reproduce this error by cycling your connection and booting the players, and then having them head to extract in their own clients when the Aki server reconnects to them. There will be an error message referencing a "players" variable in the server log. I believe it's related.

**Comment by Daemris** [comment] 2024-06-17 17:21
@fariparedes yeah that's the players variable I was talking about. didn't have other players to produce the trace, thank you.

**Comment by Daemris** [comment] 2024-06-18 22:27
![image](https://github.com/project-fika/Fika-Server/assets/12958453/6f36ad33-fece-42ca-aa80-085a44fd6cc0)

Here is a picture of the trace. You can also cause this error by leaving a raid in the esc menu before all clients are disconnected.

**Comment by fariparedes** [comment] 2024-06-19 01:32
Yep, that looks like the one I got!

**Comment by Lacyway** [comment] 2024-06-19 20:13
This should be fixed with https://github.com/project-fika/Fika-Server/pull/32, if this issue arises again after 3.9 please let us know.

**Closed by Lacyway** 2024-06-19 20:13 UTC
