### ISSUE TITLE
Items sent to other players from inside a container are lost

### ISSUE THREAD

**Issue by fariparedes** [project-fika/Fika-Server#28] opened 2024-06-14 03:33 UTC
As mentioned in the title, when I try to send an item from my scav junk box to another player, it never arrives. If I send it from my stash, it works fine. I suspect that the "parent" ID is not stripped from sent items, so it just gets orphaned and lost to the void.

**Comment by Lacyway** [comment] 2024-06-14 06:04
We're aware of this one and I think we knew what the actual issue is.
@nexus4880 did you figure it out?

**Comment by Lacyway** [comment] 2024-07-08 07:44
We're unable to reproduce this in 3.9, closing.

**Closed by Lacyway** 2024-07-08 07:44 UTC
