### ISSUE TITLE
Items that are insured will come back even if players pick it up

### ISSUE THREAD

**Issue by allegedflora** [project-fika/Fika-Server#12] opened 2024-05-04 05:20 UTC
IF you insure an item, die, and have one of your coop members pick it up. It'll still come back to your stash, and the item that your coop member picked up will still exist.

**Comment by Lacyway** [comment] 2024-05-04 12:54
This is not caused by the server itself, rather a limitation due to SPT being designed for single player. I guess what could be done is loop through all insured items at the end of a raid and see if another player is holding them, and if so remove them.

**Comment by fariparedes** [comment] 2024-06-14 03:35
Possibly you could check all the items present on someone when they extract, and add them to a list of "stolen" items stored on the raid if they are not insured by the person who extracted with them. Then, when the raid ends, remove them from insurance. This would also allow AI to steal your insured items with mods like Looting Bots.

**Comment by fariparedes** [comment] 2024-06-17 16:50
Oh yeah-- and also quest items that you plant which can be insured, like the SV-98s needed for several quests.

**Comment by ArchangelWTF** [comment] 2024-08-29 16:37
Will be fixed in 3.10

**Closed by ArchangelWTF** 2024-08-29 16:37 UTC
Labels: bug
